language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t iamanh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true iamanh/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "arn:aws:elasticbeanstalk:eu-north-1:918847403423:application/docker-react"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
